version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
      CLIENT_URL: http://localhost:3000
      SOCKET_PATH: /socket.io  
      DEBUG: socket.io:*
      DATABASE_URL: postgresql://user:password@db:5432/mydb?schema=public
      WS_PING_TIMEOUT: "60000"
      WS_PING_INTERVAL: "25000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: